Dynamic programming

In [8]:
import numpy as np

aas = {'A':71,
'R': 156,
'N': 114,
'D': 115,
'C': 103,
'E': 129,
'Q': 128,
'G': 57,
'H': 137,
'I': 113,
'L': 113,
'K': 128,
'M': 131,
'F': 147,
'P': 97,
'S': 87,
'T': 101,
'W': 186,
'Y': 163,
'V': 99}

dWeights = dict()
dWeights[0] = 1
dPep = dict()
dPep[0] = ['']

#Generate dict with all peptide weights
for i in range(1, 3001):
    found_matches = 0
    for a in aas:
        weight = aas[a]
        prev = i - weight
        if dWeights.get(prev) is not None:
            found_matches += dWeights.get(prev)

    dWeights[i] = found_matches


In [13]:

print(dWeights[200])

10


Needleman wunch-  algorithm for global alignments

Goal: Align two sequences a1....an and b1...bm
Score of match/missmatch between amino acids a,b are given by scorematrix d(a,b)
Score of in/del given as d(-,b)=d(a,-)=g

NW: Score of an optimal alignment is given by the recursion

S(0,j) = j*g
S(i,0) = i*g
S(i,j) = max(S(i-1,j-1) + d(a(i),b(j)), S(i-1,j) + g, S(i,j-1) + g)

Align GAC and ACG
use d(a,b) {1 if a=b, -1 if a or b is '-' or a != b)
 
   -   A  C  G
 -  0 -1 -2 -3  
 G -1            -1
 A -2
 C -3

In [4]:
PAM250 = {
'A': {'A': 2,  'C': -2, 'D':  0, 'E': 0, 'F': -3, 'G':  1, 'H': -1, 'I': -1, 'K': -1, 'L': -2, 'M': -1, 'N':  0, 'P':  1, 'Q':  0, 'R': -2, 'S':  1, 'T':  1, 'V':  0, 'W': -6, 'Y': -3},
'C': {'A': -2, 'C': 12, 'D': -5, 'E':-5, 'F': -4, 'G': -3, 'H': -3, 'I': -2, 'K': -5, 'L': -6, 'M': -5, 'N': -4, 'P': -3, 'Q': -5, 'R': -4, 'S':  0, 'T': -2, 'V': -2, 'W': -8, 'Y':  0},
'D': {'A': 0,  'C': -5, 'D':  4, 'E': 3, 'F': -6, 'G':  1, 'H':  1, 'I': -2, 'K':  0, 'L': -4, 'M': -3, 'N':  2, 'P': -1, 'Q':  2, 'R': -1, 'S':  0, 'T':  0, 'V': -2, 'W': -7, 'Y': -4},
'E': {'A': 0,  'C': -5, 'D':  3, 'E': 4, 'F': -5, 'G':  0, 'H':  1, 'I': -2, 'K':  0, 'L': -3, 'M': -2, 'N':  1, 'P': -1, 'Q':  2, 'R': -1, 'S':  0, 'T':  0, 'V': -2, 'W': -7, 'Y': -4},
'F': {'A': -3, 'C': -4, 'D': -6, 'E':-5, 'F':  9, 'G': -5, 'H': -2, 'I':  1, 'K': -5, 'L':  2, 'M':  0, 'N': -3, 'P': -5, 'Q': -5, 'R': -4, 'S': -3, 'T': -3, 'V': -1, 'W':  0, 'Y':  7},
'G': {'A': 1,  'C': -3, 'D':  1, 'E': 0, 'F': -5, 'G':  5, 'H': -2, 'I': -3, 'K': -2, 'L': -4, 'M': -3, 'N':  0, 'P':  0, 'Q': -1, 'R': -3, 'S':  1, 'T':  0, 'V': -1, 'W': -7, 'Y': -5},
'H': {'A': -1, 'C': -3, 'D':  1, 'E': 1, 'F': -2, 'G': -2, 'H':  6, 'I': -2, 'K':  0, 'L': -2, 'M': -2, 'N':  2, 'P':  0, 'Q':  3, 'R':  2, 'S': -1, 'T': -1, 'V': -2, 'W': -3, 'Y':  0},
'I': {'A': -1, 'C': -2, 'D': -2, 'E':-2, 'F':  1, 'G': -3, 'H': -2, 'I':  5, 'K': -2, 'L':  2, 'M':  2, 'N': -2, 'P': -2, 'Q': -2, 'R': -2, 'S': -1, 'T':  0, 'V':  4, 'W': -5, 'Y': -1},
'K': {'A': -1, 'C': -5, 'D':  0, 'E': 0, 'F': -5, 'G': -2, 'H':  0, 'I': -2, 'K':  5, 'L': -3, 'M':  0, 'N':  1, 'P': -1, 'Q':  1, 'R':  3, 'S':  0, 'T':  0, 'V': -2, 'W': -3, 'Y': -4},
'L': {'A': -2, 'C': -6, 'D': -4, 'E':-3, 'F':  2, 'G': -4, 'H': -2, 'I':  2, 'K': -3, 'L':  6, 'M':  4, 'N': -3, 'P': -3, 'Q': -2, 'R': -3, 'S': -3, 'T': -2, 'V':  2, 'W': -2, 'Y': -1},
'M': {'A': -1, 'C': -5, 'D': -3, 'E':-2, 'F':  0, 'G': -3, 'H': -2, 'I':  2, 'K':  0, 'L':  4, 'M':  6, 'N': -2, 'P': -2, 'Q': -1, 'R':  0, 'S': -2, 'T': -1, 'V':  2, 'W': -4, 'Y': -2},
'N': {'A': 0,  'C': -4, 'D':  2, 'E': 1, 'F': -3, 'G':  0, 'H':  2, 'I': -2, 'K':  1, 'L': -3, 'M': -2, 'N':  2, 'P':  0, 'Q':  1, 'R':  0, 'S':  1, 'T':  0, 'V': -2, 'W': -4, 'Y': -2},
'P': {'A': 1,  'C': -3, 'D': -1, 'E':-1, 'F': -5, 'G':  0, 'H':  0, 'I': -2, 'K': -1, 'L': -3, 'M': -2, 'N':  0, 'P':  6, 'Q':  0, 'R':  0, 'S':  1, 'T':  0, 'V': -1, 'W': -6, 'Y': -5},
'Q': {'A': 0,  'C': -5, 'D':  2, 'E': 2, 'F': -5, 'G': -1, 'H':  3, 'I': -2, 'K':  1, 'L': -2, 'M': -1, 'N':  1, 'P':  0, 'Q':  4, 'R':  1, 'S': -1, 'T': -1, 'V': -2, 'W': -5, 'Y': -4},
'R': {'A': -2, 'C': -4, 'D': -1, 'E':-1, 'F': -4, 'G': -3, 'H':  2, 'I': -2, 'K':  3, 'L': -3, 'M':  0, 'N':  0, 'P':  0, 'Q':  1, 'R':  6, 'S':  0, 'T': -1, 'V': -2, 'W':  2, 'Y': -4},
'S': {'A': 1,  'C':  0, 'D':  0, 'E': 0, 'F': -3, 'G':  1, 'H': -1, 'I': -1, 'K':  0, 'L': -3, 'M': -2, 'N':  1, 'P':  1, 'Q': -1, 'R':  0, 'S':  2, 'T':  1, 'V': -1, 'W': -2, 'Y': -3},
'T': {'A': 1,  'C': -2, 'D':  0, 'E': 0, 'F': -3, 'G':  0, 'H': -1, 'I':  0, 'K':  0, 'L': -2, 'M': -1, 'N':  0, 'P':  0, 'Q': -1, 'R': -1, 'S':  1, 'T':  3, 'V':  0, 'W': -5, 'Y': -3},
'V': {'A': 0,  'C': -2, 'D': -2, 'E':-2, 'F': -1, 'G': -1, 'H': -2, 'I':  4, 'K': -2, 'L':  2, 'M':  2, 'N': -2, 'P': -1, 'Q': -2, 'R': -2, 'S': -1, 'T':  0, 'V':  4, 'W': -6, 'Y': -2},
'W': {'A': -6, 'C': -8, 'D': -7, 'E':-7, 'F':  0, 'G': -7, 'H': -3, 'I': -5, 'K': -3, 'L': -2, 'M': -4, 'N': -4, 'P': -6, 'Q': -5, 'R':  2, 'S': -2, 'T': -5, 'V': -6, 'W': 17, 'Y':  0},
'Y': {'A': -3, 'C':  0, 'D': -4, 'E':-4, 'F':  7, 'G': -5, 'H':  0, 'I': -1, 'K': -4, 'L': -1, 'M': -2, 'N': -2, 'P': -5, 'Q': -4, 'R': -4, 'S': -3, 'T': -3, 'V': -2, 'W':  0, 'Y': 10}}


In [59]:
PAM250['A']['A']

2

In [65]:
import numpy as np

def nw(seq1, seq2):
    iSeq1, iSeq2 = len(seq1), len(seq2)
    mat = np.zeros((iSeq1+1, iSeq2+1))
    steps = np.zeros((iSeq1+1, iSeq2+1))
    g = -1

    for i in range(0, iSeq1+1):
        mat[i, 0] = i * g
    
    for j in range(0, iSeq2+1):
        mat[0,j] = j * g
    
    #Generate matrix
    for i in range(1, iSeq1+1):
        for j in range(1, iSeq2+1):
            #3 cases: insert, delete, match
            insert = mat[i][j-1]+g
            delete = mat[i-1][j]+g
            match = int(mat[i-1][j-1]+ PAM250[seq1[i-1]][seq2[j-1]])
            score = max(insert, delete, match)
            
            mat[i][j] = score
            
            if score == insert:
                steps[i,j] = 1
            elif score == delete:
                steps[i,j] = -1
            elif score == match:
                steps[i,j] = 0

    #print mat
    print steps

    #Traverse matrix from bottom right
    iPos, jPos = iSeq1, iSeq2
    a1 = ''
    a2 = ''    
    while iPos > 0 and jPos > 0:   
        if steps[iPos][jPos] == 0:
            a1 += seq1[iPos-1]
            a2 += seq2[jPos-1]
            iPos -= 1
            jPos -= 1
            
        elif steps[iPos][jPos] == -1:
            a1 += seq1[iPos-1]
            a2 += '-'
            iPos -= 1
            
        elif steps[iPos][jPos] == 1:
            a1 += '-'
            a2 += seq2[jPos-1]
            jPos -= 1
    
    print a1[::-1]
    print a2[::-1]

    
nw('CANANAS','ANNANAS')


[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.]
 [ 0. -1.  0.  1.  1.  1.  1.  1.]
 [ 0. -1. -1.  0.  0.  1.  1.  1.]
 [ 0. -1. -1.  0.  1.  0.  1.  1.]
 [ 0. -1. -1. -1.  0.  1.  0.  1.]
 [ 0. -1. -1. -1. -1.  0. -1.  0.]]
AN-ANAS
ANNANAS
